name: Build GearGlimpseRevolution

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/*"

jobs:
  build:
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: nab138/theos-action@main
        with:
          cache-dir-theos: ${{ github.workspace }}/theos
          cache-dir-sdks: ${{ github.workspace }}/theos/sdks

      - name: Cache Visp3 Framework
        uses: actions/cache@v4
        id: cache-visp3
        with:
          path: ${{ github.workspace }}/theos/lib/visp3.framework
          key: ${{ runner.os }}-visp3-2022-04-07

      - name: Cache opencv2 Framework
        uses: actions/cache@v4
        id: cache-opencv2
        with:
          path: ${{ github.workspace }}/theos/lib/opencv2.framework
          key: ${{ runner.os }}-opencv2-2022-04-07

      - name: Download Visp3 & Opencv Framework
        if: steps.cache-visp3.outputs.cache-hit != 'true' || steps.cache-opencv2.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ github.workspace }}/theos/lib
          curl -L https://visp-doc.inria.fr/download/snapshot/ios/visp3.framework-2022-04-07.zip -o ${{ github.workspace }}/theos/lib/visp3.framework-2022-04-07.zip
          unzip -o ${{ github.workspace }}/theos/lib/visp3.framework-2022-04-07.zip -d ${{ github.workspace }}/theos/lib
          rm ${{ github.workspace }}/theos/lib/visp3.framework-2022-04-07.zip

      - name: Download 3044 Robot Model
        uses: robinraju/release-downloader@v1.10
        with:
          tarBall: false
          zipBall: false
          out-file-path: "Resources"
          tag: "assets-v2"
          fileName: "R0xstar.usdz"

      - name: Download KitBot Robot Model
        uses: robinraju/release-downloader@v1.10
        with:
          tarBall: false
          zipBall: false
          out-file-path: "Resources"
          tag: "assets-v2"
          fileName: "2024KitBot.usdz"

      - name: Build
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GearGlimpseRevolution
          path: packages/*.ipa

      - name: Set Release Version
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/heads/release/}"

      - name: Create Release
        if: startsWith(github.ref, 'refs/heads/release/')
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.version.outputs.version }}"
          prerelease: false
          draft: true
          title: "GearGlimpseRevolution ${{ steps.version.outputs.version }}"
          files: |
            packages/*.ipa
