name: Build GearGlimpseRevolution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Theos
        uses: beerpiss/theos-action@v1.7.0

      - name: Build
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GearGlimpseRevolution
          path: packages/*.ipa
